name: 'Install CloudTruth CLI'
description: 'Install the CloudTruth CLI'
inputs:
  version:
    required: false
    default: '0.1.3'
branding:
  icon: 'terminal'
  color: 'green'
runs:
  using: 'node12'
  main: 'index.js'