name: CloudTruth CLI Action
on: [push]

jobs:
  get_version:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: get Version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: OS CLI Path
        uses: ./ # Uses an action in the root directory
        id: install
      - name: Test CLI
        run: cloudtruth -V